'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import styles from '../dashboard.module.css'
import pStyles from './posts.module.css'

type Post = {
  id: string
  content: string
  status: string
  created_at: string
  posted_at: string | null
  image_url: string | null
}

function PostCard({ post, onStatus, onDelete, onLinkedIn }: {
  post: Post
  onStatus: (id: string, status: string) => void
  onDelete: (id: string) => void
  onLinkedIn: (id: string) => void
}) {
  const lines = post.content.split('\n').filter(l => l.trim())
  const firstLine = lines[0] || ''
  const rest = lines.slice(1).join('\n')

  const statusConfig: Record<string, { label: string; dot: string; bg: string; color: string }> = {
    pending:  { label: 'Pending Review', dot: '#F59E0B', bg: '#FFFBEB', color: '#92400E' },
    approved: { label: 'Approved',       dot: '#10B981', bg: '#ECFDF5', color: '#065F46' },
    posted:   { label: 'Posted',         dot: '#2563EB', bg: '#EFF6FF', color: '#1E40AF' },
    skipped:  { label: 'Skipped',        dot: '#94A3B8', bg: '#F8FAFC', color: '#475569' },
  }
  const s = statusConfig[post.status] || statusConfig.pending

  return (
    <div className={pStyles.postCard}>
      {/* Meta row */}
      <div className={pStyles.metaRow}>
        <div className={pStyles.metaLeft}>
          <div className={pStyles.metaGenerated}>Generated by PostPilot AI</div>
          <div className={pStyles.metaDate}>
            {new Date(post.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
          </div>
        </div>
        <div className={pStyles.statusBadge} style={{ background: s.bg, color: s.color }}>
          <span className={pStyles.statusDot} style={{ background: s.dot }} />
          {s.label}
        </div>
      </div>

      {/* Post content with hierarchy */}
      <div className={pStyles.postContent}>
         <p className={pStyles.firstLine} style={{ whiteSpace: 'pre-line' }}>{firstLine}</p>
        {rest && <p className={pStyles.restContent} style={{ whiteSpace: 'pre-line' }}>{rest}</p>}
      </div>

      {/* Image card */}
      {post.image_url && (
        <img src={post.image_url} alt="Post card" className={pStyles.postImage} />
      )}

      {/* Actions */}
      <div className={pStyles.postActions}>
        {post.status === 'pending' && (
          <button className={pStyles.approveBtn} onClick={() => onStatus(post.id, 'approved')}>
            <i className="ti ti-check" /> Approve
          </button>
        )}
        {post.status === 'approved' && (
          <>
            <button className={pStyles.linkedinBtn} onClick={() => onLinkedIn(post.id)}>
              <i className="ti ti-brand-linkedin" /> Post to LinkedIn
            </button>
            <button className={pStyles.unapproveBtn} onClick={() => onStatus(post.id, 'pending')}>
              <i className="ti ti-arrow-back" /> Unapprove
            </button>
          </>
        )}
        {post.status !== 'skipped' && post.status !== 'posted' && (
          <button className={pStyles.skipBtn} onClick={() => onStatus(post.id, 'skipped')}>
            <i className="ti ti-x" /> Skip
          </button>
        )}
        <button className={pStyles.deleteBtn} onClick={() => onDelete(post.id)}>
          <i className="ti ti-trash" /> Delete
        </button>
      </div>
    </div>
  )
}

export default function PostsPage() {
  const router = useRouter()
  const [posts, setPosts] = useState<Post[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('all')
  const [email, setEmail] = useState('')

  useEffect(() => {
    async function load() {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) { router.push('/login'); return }
      setEmail(user.email || '')
      const { data } = await supabase
        .from('posts')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
      if (data) setPosts(data)
      setLoading(false)
    }
    load()
  }, [router])

  async function updateStatus(id: string, status: string) {
    await supabase.from('posts').update({ status }).eq('id', id)
    setPosts(prev => prev.map(p => p.id === id ? { ...p, status } : p))
  }

  async function deletePost(id: string) {
    if (!confirm('Delete this post?')) return
    await supabase.from('posts').delete().eq('id', id)
    setPosts(prev => prev.filter(p => p.id !== id))
  }

  async function postToLinkedIn(postId: string) {
    const { data: { session } } = await supabase.auth.getSession()
    const res = await fetch('/api/linkedin/post', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${session?.access_token}`
      },
      body: JSON.stringify({ postId })
    })
    const data = await res.json()
    if (data.success) {
      setPosts(prev => prev.map(p => p.id === postId ? { ...p, status: 'posted' } : p))
    } else {
      alert('Failed to post: ' + data.error)
    }
  }

  async function handleSignOut() {
    await supabase.auth.signOut()
    router.push('/')
  }

  const filtered = filter === 'all' ? posts : posts.filter(p => p.status === filter)

  if (loading) return (
    <div className={styles.loading}>
      <i className="ti ti-loader-2" style={{ fontSize: 28, color: '#2563EB' }} />
    </div>
  )

  return (
    <div className={styles.page}>
      <aside className={styles.sidebar}>
        <div className={styles.sidebarLogo}>
          <i className="ti ti-brand-linkedin" />Post<em>Pilot</em> AI
        </div>
        <nav className={styles.nav}>
          <Link href="/dashboard" className={styles.navItem}><i className="ti ti-layout-dashboard" /> Dashboard</Link>
          <Link href="/dashboard/posts" className={`${styles.navItem} ${styles.active}`}><i className="ti ti-file-text" /> Posts</Link>
          <Link href="/dashboard/settings" className={styles.navItem}><i className="ti ti-settings" /> Settings</Link>
        </nav>
        <div className={styles.sidebarBottom}>
          <div className={styles.userInfo}>
            <div className={styles.avatar}>{email[0]?.toUpperCase()}</div>
            <div><div className={styles.userEmail}>{email}</div></div>
          </div>
          <button className={styles.signOut} onClick={handleSignOut}>
            <i className="ti ti-logout" /> Sign out
          </button>
        </div>
      </aside>

      <main className={styles.main}>
        <div className={styles.header}>
          <div>
            <h1 className={styles.pageTitle}>All Posts</h1>
            <p className={styles.pageSubtitle}>{posts.length} posts total</p>
          </div>
          <Link href="/dashboard" className={styles.generateBtn}>
            <i className="ti ti-arrow-left" /> Back
          </Link>
        </div>

        <div className={pStyles.tabs}>
          {['all', 'pending', 'approved', 'posted', 'skipped'].map(f => (
            <button
              key={f}
              className={`${pStyles.tab} ${filter === f ? pStyles.activeTab : ''}`}
              onClick={() => setFilter(f)}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
              <span className={pStyles.count}>
                {f === 'all' ? posts.length : posts.filter(p => p.status === f).length}
              </span>
            </button>
          ))}
        </div>

        {filtered.length === 0 ? (
          <div className={pStyles.emptyState}>
            <div className={pStyles.emptyIcon}>
              <i className="ti ti-file-plus" />
            </div>
            <h3 className={pStyles.emptyTitle}>No posts yet</h3>
            <p className={pStyles.emptyDesc}>Generate your first LinkedIn post in seconds.</p>
            <Link href="/dashboard" className={pStyles.emptyBtn}>
              <i className="ti ti-sparkles" /> Generate Post
            </Link>
          </div>
        ) : (
          <div className={pStyles.postsList}>
            {filtered.map(post => (
              <PostCard
                key={post.id}
                post={post}
                onStatus={updateStatus}
                onDelete={deletePost}
                onLinkedIn={postToLinkedIn}
              />
            ))}
          </div>
        )}
      </main>
    </div>
  )
}